# Generated by Django 4.1 on 2022-08-20 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storedetails',
            unique_together=set(),
        ),
    ]
