# Generated by Django 4.1 on 2022-08-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_orderdetails_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='updated_on',
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='created_on',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
